import { Movie } from "./types";

export const Sample: Array<Movie> = [
    {
        imdb_title_id: "tt0000009",
        title: "Miss Jerry",
        original_title: "Miss Jerry",
        year: 1894,
        date_published: "1894-10-09",
        genre: ["Romance"],
        duration: 45,
        country: ["USA"],
        language: ["None"],
        director: ["Alexander Black"],
        writer: ["Alexander Black"],
        production_company: "Alexander Black Photoplays",
        actors: ["Blanche Bayliss, William Courtenay, Chauncey Depew"],
        description: "The adventures of a female reporter in the 1890s.",
        avg_vote: 5.9,
        votes: 154,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "",
        metascore: null,
        reviews_from_users: 1,
        reviews_from_critics: 2
    },
    {
        imdb_title_id: "tt0000574",
        title: "The Story of the Kelly Gang",
        original_title: "The Story of the Kelly Gang",
        year: 1906,
        date_published: "1906-12-26",
        genre: ["Biography", "Crime", "Drama"],
        duration: 70,
        country: ["Australia"],
        language: ["None"],
        director: ["Charles Tait"],
        writer: ["Charles Tait"],
        production_company: "J. and N. Tait",
        actors: [
            "Elizabeth Tait", 
            "John Tait", 
            "Norman Campbell", 
            "Bella Cola", 
            "Will Coyne", 
            "Sam Crewes", 
            "Jack Ennis", 
            "John Forde",
            "Vera Linden",
            "Mr. Marshall", 
            "Mr. McKenzie", 
            "Frank Mills",
            "Ollie Wilson"
        ],
        description: "True story of notorious Australian outlaw Ned Kelly (1855-80).",
        avg_vote: 6.1,
        votes: 589,
        budget: "$ 2250",
        usa_gross_income: "",
        worlwide_gross_income: "",
        metascore: null,
        reviews_from_users: 7,
        reviews_from_critics: 7
    },
    {
        imdb_title_id: "tt0001892",
        title: "Den sorte drøm",
        original_title: "Den sorte drøm",
        year: 1911,
        date_published: "1911-08-19",
        genre: ["Drama"],
        duration: 53,
        country: ["Germany", "Denmark"],
        language: [],
        director: ["Urban Gad"],
        writer: ["Urban Gad, Gebhard Schätzler-Perasini"],
        production_company: "Fotorama",
        actors: ["Asta Nielsen, Valdemar Psilander, Gunnar Helsengreen, Emil Albes, Hugo Flink, Mary Hagen"],
        description: "Two men of high rank are both wooing the beautiful and famous equestrian acrobat Stella. While Stella ignores the jeweler Hirsch, she accepts Count von Waldberg's offer to follow her home, ...",
        avg_vote: 5.8,
        votes: 188,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "",
        metascore: null,
        reviews_from_users: 5,
        reviews_from_critics: 2
    }
];